### ISSUE TITLE
Display the time it takes to complete a workshop and module

### ISSUE THREAD

**Issue by jorgemoralespou** [openshift-evangelists/workshopper#15]
In the workshop and module list it would be nice to have an indication of the time it takes to complete.

Example:
https://kiosk-dot-codelabs-site.appspot.com/devoxx

![image](https://cloud.githubusercontent.com/assets/78350/23763524/3f5df29c-04fa-11e7-994c-89fdc7d442c2.png)

**Comment by jorgemoralespou** [comment]
Additionally, time remaining can be displayed when in every module.

Example:
![image](https://cloud.githubusercontent.com/assets/78350/23763763/2df46a9e-04fb-11e7-9382-1f247b61525a.png)

**Comment by marekjelen** [comment]
can you propose updated to _modules.yml structure to track this information?

**Comment by marekjelen** [comment]
@jorgemoralespou is this still valid request?

**Comment by jorgemoralespou** [comment]
Yes.

```
  module:
    name: "String"
    vars:
      <LIST of key:value>
    revisions:
      <LIST of REVISIONS>
    duration: <TIME in MINUTES to complete the module> 
```

Additionally, it would be nice if we could have the sum of times it takes to complete a whole workshop, in the workshop main page or header.
